CREATE DATABASE walletdb OWNER postgres;

GRANT ALL PRIVILEGES ON DATABASE walletdb TO postgres;

\c walletdb

CREATE TABLE customer (
  id UUID PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE account (
  id UUID PRIMARY KEY,
  customer_id UUID REFERENCES customer(id) ON DELETE CASCADE,
  balance NUMERIC(10, 2) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE transaction (
  id UUID PRIMARY KEY,
  account_id UUID REFERENCES account(id) ON DELETE CASCADE,
  amount NUMERIC(10, 2) NOT NULL,
  type VARCHAR(50) NOT NULL,
  status VARCHAR(50) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
);
